{% set name = "python-chromedriver-binary" %}
{% set version = "2.38.0" %}
{% set chromium_version = "2.38" %}
{% set sha256 = "1fdfbabd01ebbb4089c4b691904191cdce0415b858f509e255fb39a7ed24b42d" %}
{% set chromium_win32_sha256 = "a8fa028acebef7b931ef9cb093f02865f9f7495e49351f556e919f7be77f072e" %}    # [win]
{% set chromium_mac64_sha256 = "6da3e8e3604d332b73f961495cb6d01d79d995b456778a3bda87df236c138462" %}    # [osx]
{% set chromium_linux64_sha256 = "519e8f69824ab63d3f223edd19f92128007f78bfb51f878ca2a2d70c6a0f294e" %}  # [linux64]

package:
  name: {{ name|lower }}-suite
  version: {{ version }}

source:
  - url: https://github.com/danielkaiser/{{ name }}/archive/v{{ version }}.tar.gz
    fn: {{ name }}-{{ version }}.tar.gz
    sha256: {{ sha256 }}
  - url: https://chromedriver.storage.googleapis.com/{{ chromium_version }}/chromedriver_win32.zip    # [win]
  - url: https://chromedriver.storage.googleapis.com/{{ chromium_version }}/chromedriver_mac64.zip    # [osx]
  - url: https://chromedriver.storage.googleapis.com/{{ chromium_version }}/chromedriver_linux64.zip  # [linux64]
    sha256: {{ chromium_win32_sha256 }}  # [win]
    sha256: {{ chromium_mac64_sha256 }}  # [osx]
    sha256: {{ chromium_linux64_sha256 }}  # [linux]
    folder: chromedriver

build:
  number: 0
  skip: True  # [linux32 or ppc64le]

outputs:
  - name: chromedriver-binary
    version: {{ chromium_version }}
    script: install-chromedriver-binary.sh   # [win]
    script: install-chromedriver-binary.bat  # [win]
    activate_in_script: True
    # Ah the joy of binaries:
    build:
      activate_in_script: True
      missing_dso_whitelist:
        - /usr/lib/libbsm.0.dylib     # [osx]
        - /usr/lib/libresolv.9.dylib  # [osx]
        # We use install_name_tool on this one instead:
        # - /usr/lib/libc++.1.dylib   # [osx]
        # Could probably use cdt packages here which would allow more options latre
        # (o.e. recommendations for the things to install w/ system package manager).
        - libglib-2.0.so.0            # [linux]
        - libgcc_s.so.1               # [linux]
        - libnspr4.so                 # [linux]
        - libnss3.so                  # [linux]
        - libpthread.so.0             # [linux]
        - libdl.so.2                  # [linux]
        - librt.so.1                  # [linux]
        - libnssutil3.so              # [linux]
        - libc.so.6                   # [linux]
        - libm.so.6                   # [linux]
        - libX11.so.6                 # [linux]
    requirements:
      build:
        - cctools                     # [osx]
      run:
        - libcxx >=4.0.1              # [osx]

  - name: python-chromedriver-binary
    version: {{ version }}
    script: install-python-chromedriver-binary.sh   # [not win]
    script: install-python-chromedriver-binary.bat  # [win]
    build:
      activate_in_script: True
    requirements:
      host:
        - python
        - pip
        - setuptools
        - pandoc
        - {{ pin_subpackage('chromedriver-binary', exact=True) }}
      run:
        - python
        - {{ pin_subpackage('chromedriver-binary', exact=True) }}
    about:
      home: https://sites.google.com/a/chromium.org/chromedriver/
      license: 3-Clause BSD
      license_family: BSD
      license_file: LICENSE
      summary: WebDriver for Chrome (binary)
      description: |
        WebDriver is an open source tool for automated testing of webapps
        across many browsers. It provides capabilities for navigating to web
        pages, user input, JavaScript execution, and more.  ChromeDriver
        is a standalone server which implements WebDriver's wire protocol
        for Chromium.

    test:
      requires:
        - setuptools
      imports:
        - chromedriver_binary
      commands:
        - chromedriver-path
      about:
        home: https://github.com/danielkaiser/python-chromedriver-binary
        license: MIT
        license_family: MIT
        license_file: LICENSE
        summary: 'Downloads and installs the chromedriver binary version'
        description: |
          Downloads and installs the chromedriver binary for automated
          testing of webapps. The installer supports Linux, MacOS and Windows
          operating systems.



extra:
  recipe-maintainers:
    - igortg
    - williamjamir
