travis:
  secure:
    BINSTAR_TOKEN: 1Q38IOxUwh7UTALzIzu3onEiZiV2SpGZbPUe9ZuEjXECMim1YYF5hS/nusc+3G/+jJJF6r6aSbG+QgVu/QAODZ8v08ErDam8JvZTaYMlptZSIwYjbjl408vOf0ySSZcxC46nh4PJSRSwOhyTBVyx7LCoN2Mvt3IbZsxlO7HGyot9/9fY63cWUdYMSJAhZvhQ2pQWr33pNlKWVI5CbSp7XtOXeWddXspeFJT5OIFZjL8DZFGT+zfBuH2AILkM4PIy1w9GymrDQb7fvOwCa1ez2XJB2HiM1emibHPoEt7ZuZfKuB/Iqqn/g5nuIAzgUzSFcCyWqDo+YRk6h/mt3ueApZZUepZMwUyNG7hI0HMq1pb7XqxQLu/HUL5ntNmehROMGuLheai6ZqHPorsBIl4QMA6jtjf30jiE8CpoWFpkzJcAF9Ba3vIcwvtV4gJmgWBT6S01n1znmWW1SVrPkxvomiEhNF7QvGX1qFiLRB9FBshXquUldAaCOpM/ECFdMhiurrD/Eh4iTEdx+Tg0wLUSnEpDk2kkCUc9SDpYRn2ldJjYRadhaRNIhzZdMfJ3bDpOsiqFCU8SrexlCO7I2vUuwxBDHEVxjIQMljTW4QRL+Hq9E3fnCUe00Ode9N8QB0ix9XPfeWHa0F+EsiiwbzUu23LlfOqvMNxCmSr2Izad6lQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
